### ISSUE TITLE
Uncaught TypeError: Cannot read property 'focus' of undefined

### ISSUE THREAD

**Issue by 2f-concept** [diegoddox/react-redux-toastr#219]
full message : 
Uncaught TypeError: Cannot read property 'focus' of undefined  at ToastrBox.js:234

toast works great but I got this error

my package.json:
````
  "dependencies": {
    "animated": "^0.2.2",
    "apisauce": "^1.0.1",
    "detect-browser": "^3.0.1",
    "detect-browser-language": "^0.0.1",
    "js-sha512": "^0.8.0",
    "mdbreact": "4.8.4",
    "prop-types": "^15.6.0",
    "react": "16.7.0-alpha.2",
    "react-dom": "^16.6.3",
    "react-intl": "^2.7.2",
    "react-redux": "^6.0.0",
    "react-redux-toastr": "^7.4.4",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "react-scripts": "^2.1.1",
    "react-transition-group": "^2.5.0",
    "redux": "^4.0.1",
    "redux-persist": "^5.10.0",
    "redux-saga": "^0.16.2",
    "reduxsauce": "^1.0.0",
    "seamless-immutable": "^7.1.4",
    "styled-components": "^4.1.2"
  },
````

**Comment by diegoddox** [comment]
This should be fixed on the latest version.

**Comment by koraydemirci** [comment]
I installed the latest version ("^7.4.5") but unfortunately the error is still there.

**Comment by koraydemirci** [comment]
> This should be fixed on the latest version.

Hello, I installed the latest version ("^7.4.5") but unfortunately the error is still there.

**Comment by wings1yte** [comment]
Still reproducable in 7.4.8. Pls add check not only of undefined, keep in mind that closeButton may be null.
